stages:

  # added dedicated cloud ingestion stage
  # this stage downloads raw dataset from AWS S3
  # and saves it locally into data/raw/
  download_data:

    cmd: python src/pipelines/download_data_pipeline.py

    deps:
      - src/pipelines/download_data_pipeline.py
      - src/data/load_data.py
      - src/data/s3_loader.py

    outs:
      - data/raw/bengaluru_house_prices.csv

  preprocess:

    cmd: python src/pipelines/preprocess_pipeline.py

    deps:
      - data/raw/bengaluru_house_prices.csv
      - src/pipelines/preprocess_pipeline.py

    outs:
      - data/processed/new_data.csv
      - data/processed/train_data.csv


  train:

    cmd: python src/pipelines/train_pipeline.py

    deps:
      - data/processed/train_data.csv
      - src/pipelines/train_pipeline.py